
name: InChI build matrix

on:
  push:
  workflow_dispatch:

jobs:
  build_linux:
    name: Build on Ubuntu 22.04
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake ninja-build

      - name: Build InChI
        run: |
          cmake -B builddir -G Ninja
          cmake --build builddir

  build-windows:
    name: Build on Windows Server 2019
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4

      - name: Set up Visual Studio shell
        uses: egor-tensin/vs-shell@v2
        with:
          arch: x64

      - name: Install build dependencies
        run: |
          choco install cmake ninja

      - name: Build InChI
        run: |
          cmake -B builddir -G Ninja
          cmake --build builddir


  buid-mac:
    name: Build on macOS 14
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          brew install ninja

      - name: Build InChI
        run: |
          cmake -B builddir -G Ninja
          cmake --build builddir
