name: InChI Continuous Integration

on:
  push:
    branches: [ main, rwth ]
  pull_request:
    branches: [ main, rwth ]
  workflow_dispatch:

jobs:
  test_glibc_gcc:
    runs-on: ubuntu-latest
    container: gcc:12

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e INCHI-1-TEST[invariance-tests]
      - uses: ./.github/actions/regression_tests
        with:
          artifact-name: regression-test-results_glibc_gcc
      - uses: ./.github/actions/invariance_tests
        if: '!cancelled()'
        with:
          artifact-name: invariance-test-results_glibc_gcc

  test_musl_gcc:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - uses: actions/checkout@v4
      - name: Install build and test environment
        run: |
          apk add bash git musl-dev gcc make python3 py-pip
      - name: Show Python version
        run: |
          python --version
      - name: Configure pip to break system packages
        run: |
          mkdir -p ~/.config/pip
          cat <<EOT >> ~/.config/pip/pip.conf
          [global]
          break-system-packages = true
          EOT
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e INCHI-1-TEST
      - uses: ./.github/actions/regression_tests
        with:
          artifact-name: regression-test-results_musl_gcc
      # FIXME: We don't run invariance test on alpine yet because of difficulties with RDKit installation.
