name: InChI Continuous Integration

on:
  push:
    branches: [ main, rwth ]
  pull_request:
    branches: [ main, rwth ]
  workflow_dispatch:

jobs:
  test_glibc_gcc:
    runs-on: ubuntu-latest
    container: gcc:latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: ./.github/actions/regression_tests

  test_musl_gcc:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - uses: actions/checkout@v3
      - name: Install build and test environment
        run: |
          apk add bash musl-dev gcc make python3 py-pip
      - name: Show Python version
        run: |
          python --version
      - name: Configure pip to break system packages
        run: |
          mkdir -p ~/.config/pip
          cat <<EOT >> ~/.config/pip/pip.conf
          [global]
          break-system-packages = true
          EOT
      - uses: ./.github/actions/regression_tests
