name: InChI Continuous Integration

on:
  push:
    branches: [ main, rwth ]
  pull_request:
    branches: [ main, rwth ]
  workflow_dispatch:

jobs:
  test_glibc_gcc:
    runs-on: ubuntu-latest
    container: gcc:latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/regression_tests

  test_musl_gcc:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - uses: actions/checkout@v3
      - name: Install build and test environment
        run: |
          apk add bash musl-dev gcc make python3 py-pip
      - uses: ./.github/actions/regression_tests
