name: InChI Continuous Integration

on:
  push:
    branches: [ main, rwth ]
  pull_request:
    branches: [ main, rwth ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: gcc:latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/regression_tests.yml
