name: InChI Continuous Integration

on:
  push:
    branches: [ main, rwth ]
  pull_request:
    branches: [ main, rwth ]
  workflow_dispatch:

jobs:
  test_glibc_gcc:
    runs-on: ubuntu-latest
    container: gcc:latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: ./.github/actions/regression_tests

  test_musl_gcc:
    runs-on: ubuntu-latest
    container: alpine:latest

    steps:
      - uses: actions/checkout@v3
      - name: Install build and test environment
        run: |
          apk add bash musl-dev gcc make python3 py-pip
      - name: Set up Python environment
        run: |
          python3 -m venv .env
          source .env/bin/activate
          python -m pip install --upgrade pip
        shell: bash
      - name: Show Python version
        run: |
          python --version
        shell: bash
      - uses: ./.github/actions/regression_tests
